# Working with Dictionaries, Sets, and NumPy arrays
___
**Author:** Ben Kelly 
**Version:** 1.0  
**Semester:** Spring 2024 

### Problem 1 - Language Translator.

In [7]:
span_translate = {'book': 'libro', 'chair': 'silla', 'tree': 'árbol', 'table': 'mesa', 'water': 'agua', 'woman': 'mujer', 'man': 'hombre', 'teacher': 'maestra', 'library': 'biblioteca', 'bread': 'pan', 'bathroom': 'baño', 'sun': 'sol', 'morning': 'mañana', 'sunday': 'domingo', 'car': 'coche', 'year': 'año', 'hour': 'hora', 'minute': 'minuto', 'father': 'padre', 'friend': 'amigo'}

while True:
    word = input("Enter a word to translate from English to Spanish (enter Q to stop): ")
    if word == 'Q':
        break
    translate = span_translate.get(word)
    if translate:
        print(f"The Spanish word for {word} is {translate}.")
    else:
        print(f"The Spanish word for {word} is not in this dictionary.")
        

Enter a word to translate from English to Spanish (enter Q to stop):  chair


The Spanish word for chair is silla.


Enter a word to translate from English to Spanish (enter Q to stop):  water


The Spanish word for water is agua.


Enter a word to translate from English to Spanish (enter Q to stop):  man


The Spanish word for man is hombre.


Enter a word to translate from English to Spanish (enter Q to stop):  father


The Spanish word for father is padre.


Enter a word to translate from English to Spanish (enter Q to stop):  basketball


The Spanish word for basketball is not in this dictionary.


Enter a word to translate from English to Spanish (enter Q to stop):  Q


### Problem 2 - Translating Morse Code.

In [10]:
morse_code_trans = {'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....','I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.','Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-','Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....','6': '-....', '7': '--...', '8': '---..', '9': '----.'}
def translate(sentence):
    morse_code = ''
    for character in sentence.upper():
        if character in morse_code_trans:
            morse_code += morse_code_trans[character] + ''
    return morse_code

while True:
    message = input("Enter a message to translate to Morse Code (type q to quit).")
    if message == 'q':
        break
    morse = translate(message)
    print("Morse Code Translation:", morse)
    

Enter a message to translate to Morse Code (type q to quit). How are you doing today


Morse Code Translation: ....---.--.-.-..-.-----..--..---..-.--.-----...--.--


Enter a message to translate to Morse Code (type q to quit). abc


Morse Code Translation: .--...-.-.


Enter a message to translate to Morse Code (type q to quit). I am 19


Morse Code Translation: ...---.--------.


Enter a message to translate to Morse Code (type q to quit). q


### Problem 3 - Comparing Minors/Majors.

In [12]:
comp_sci_minor = {'CS100', 'CS130', 'CS131', 'CS215', 'CS400', 'CS322', 'CS330', 'MATH120'}
bus_admin_minor = {'BUSA103', 'BUSA203', 'BUSA301', 'BUSA305', 'ACCT101', 'ECON110', 'FINA315', 'MATH125', 'MATH117'}
bus_ana_minor = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'MATH117', 'MATH125', 'MATH205'}
data_sci_major = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300', 'DS450', 'MATH205', 'MATH215', 'MATH430', 'ECON410', 'ECON322', 'ECON351', 'DS444', 'ECON110', 'ECON111', 'MATH117'}

In [13]:
bus_admin_minor & bus_ana_minor #shows the overlapping courses in Business Administration and Business Analytics

{'BUSA103', 'MATH117', 'MATH125'}

In [14]:
bus_admin_minor | comp_sci_minor #lists all unique courses in Business Administration and Business Analytics

{'ACCT101',
 'BUSA103',
 'BUSA203',
 'BUSA301',
 'BUSA305',
 'CS100',
 'CS130',
 'CS131',
 'CS215',
 'CS322',
 'CS330',
 'CS400',
 'ECON110',
 'FINA315',
 'MATH117',
 'MATH120',
 'MATH125'}

In [16]:
bus_admin_minor - bus_ana_minor #courses in Business Admin minor, not in Business Analytics

{'ACCT101', 'BUSA203', 'BUSA301', 'BUSA305', 'ECON110', 'FINA315'}

In [17]:
comp_sci_minor & data_sci_major #shows no overlap between computer science minor and data science major

set()

In [18]:
bus_ana_minor - data_sci_major #shows the only unique course not in data science major is MATH 125, but students can take Math 117 instead, which is in data science major

{'MATH125'}

### Problem 4 - Working with NumPy.

In [22]:
import numpy as np

nums1 = np.random.randint(0, 21, size = (5, 5))
nums2 = np.random.randint(0, 21, size = (5, 5))
print("Array 1 is:")
print(nums1)
print("Array 2 is:")
print(nums2)

matrix_product = nums1 * nums2
dot_product = nums1 @ nums2

print("Matrix product is:")
print(matrix_product)
print("Dot product is:")
print(dot_product)

Array 1 is:
[[14  5  3 12  7]
 [ 9  5 20 10 16]
 [ 9  9 20  8  1]
 [18 13 16  2 11]
 [ 2 20  4 10 12]]
Array 2 is:
[[ 0 17  8 10 12]
 [ 1  9  0  8  7]
 [19 16 16 15 19]
 [ 1  0  6 11  3]
 [11 18 11 20  3]]
Matrix product is:
[[  0  85  24 120  84]
 [  9  45   0  80 112]
 [171 144 320 120  19]
 [ 18   0  96  22  33]
 [ 22 360  44 200  36]]
Dot product is:
[[151 457 309 497 317]
 [571 806 628 860 601]
 [408 572 451 570 578]
 [440 877 533 766 650]
 [238 494 272 590 306]]


In [24]:
determinant_nums1 = np.linalg.det(nums1)
determinant_nums2 = np.linalg.det(nums2)
inverse_nums1 = np.linalg.inv(nums1)
inverse_nums2 = np.linalg.inv(nums2)

print(f"Determinant of Array 1 is: {determinant_nums1}")
print(f"Determinant of Array 2 is: {determinant_nums2}")

print("The inverse of Array 1 is:")
print(inverse_nums1)
print("The inverse of Array 2 is:")
print(inverse_nums2)

Determinant of Array 1 is: 1243061.9999999972
Determinant of Array 2 is: 314713.99999999977
The inverse of Array 1 is:
[[ 0.04371142 -0.02647977 -0.0080173   0.04191102 -0.02794229]
 [-0.0180715  -0.03970035  0.01744885  0.02036423  0.04335423]
 [-0.03302007  0.02316859  0.03642296 -0.00276575 -0.01212972]
 [ 0.05522814  0.00968254  0.03161065 -0.06490585  0.01173634]
 [-0.01218282  0.0547889  -0.06622839  0.01408458  0.00999628]]
The inverse of Array 2 is:
[[-0.07683802  0.02997642  0.04150753 -0.04615937  0.02068545]
 [ 0.03949618 -0.00606265 -0.01666275 -0.07440406  0.03609627]
 [ 0.08246853 -0.17211182  0.00495053  0.03659831  0.0037685 ]
 [-0.03943263  0.07443584 -0.01554427  0.06865281  0.01384114]
 [ 0.00526192  0.0613001   0.03325877  0.02379621 -0.06518299]]


In [27]:
a = np.linspace(0, 1, 20)
b = np.linspace(1, 2, 20)

a_plus_b = np.concatenate((a, b))
reshaped_array = np.reshape(a_plus_b, (10, 4))

print("Concatenated array is:")
print(a_plus_b)
print("Reshaped array is:")
print(reshaped_array)

Concatenated array is:
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.         1.         1.05263158 1.10526316 1.15789474
 1.21052632 1.26315789 1.31578947 1.36842105 1.42105263 1.47368421
 1.52631579 1.57894737 1.63157895 1.68421053 1.73684211 1.78947368
 1.84210526 1.89473684 1.94736842 2.        ]
Reshaped array is:
[[0.         0.05263158 0.10526316 0.15789474]
 [0.21052632 0.26315789 0.31578947 0.36842105]
 [0.42105263 0.47368421 0.52631579 0.57894737]
 [0.63157895 0.68421053 0.73684211 0.78947368]
 [0.84210526 0.89473684 0.94736842 1.        ]
 [1.         1.05263158 1.10526316 1.15789474]
 [1.21052632 1.26315789 1.31578947 1.36842105]
 [1.42105263 1.47368421 1.52631579 1.57894737]
 [1.63157895 1.68421053 1.73684211 1.78947368]
 [1.84210526 1.89473684 1.94736842 2.        ]]
